title: SecureX orchestration
description: >-
 Various documentation and information about SecureX orchestration 
 including atomic actions and workflows.

baseurl: "/sxo-05-security-workflows"
url: "https://ciscosecurity.github.io"

logo: "/assets/images/logo.png"

remote_theme: pmarsceill/just-the-docs

site.favicon: "/favicon.ico"

aux_links:
  "GitHub Repository":
    - "https://github.com/CiscoSecurity/sxo-05-security-workflows"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020 Cisco Systems. All content in this repository is provided AS-IS under the <a href=\"https://github.com/CiscoSecurity/sxo-05-security-workflows/blob/Main/LICENSE.md\">Cisco Sample Code License</a>."

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/CiscoSecurity/sxo-05-security-workflows"
gh_edit_branch: "Main"
gh_edit_source: docs
gh_edit_view_mode: "tree"