title: SecureX orchestration
email: support@cisco.com
description: >- # this means to ignore newlines until "baseurl:"
 Various documentation and information about SecureX orchestration 
 including atomic actions and workflows.
baseurl: "/docs"
#url: "https://ciscosecurity.github.io/sxo-05-security-workflows"
logo: "/assets/images/logo.png"

remote_theme: pmarsceill/just-the-docs

site.favicon: "/favicon.ico"

aux_links:
  "GitHub Repository":
    - "https://github.com/CiscoSecurity/sxo-05-security-workflows"