source "https://rubygems.org"

gem "github-pages", "~> 209", group: :jekyll_plugins

group :jekyll_plugins do
  
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "just-the-docs"

gem 'jekyll-redirect-from'